<?php
$helper = $this->helper('Hiddentechies\Atmag007\Helper\Data');
$enable = $helper->getConfigValue('themesettings/scrolltop/enable');
?>
<?php if ($enable) { ?>
    <a class="scrollTop" href="#" title="<?php echo __('Scroll To Top'); ?>">
        <span>
            <i class="fa fa-chevron-up" aria-hidden="true"></i>
        </span>
    </a>
    <script>
        require(['jquery'], function() {
            jQuery(document).ready(function() {
                if (jQuery(".scrollTop").length > 0) {
                    jQuery(window).scroll(function() {
                        if (jQuery(this).scrollTop() > 100) {
                            jQuery('.scrollTop').fadeIn();
                        } else {
                            jQuery('.scrollTop').fadeOut();
                        }
                    });
                    jQuery('.scrollTop').click(function() {
                        jQuery("html, body").animate({scrollTop: 0}, 600);
                        return false;
                    });
                }
            });
        });
    </script>
<?php } ?>
